* Package Management

Packages are installed as required using the function
=check-installed=. By default, melpa and gnu mirrors are used.

* Global Settings

GUI customisation includes disabling the splash screen, hiding the
toolbar and menu bar. The theme =monokai= is used.

Trailing whitespace is displayed. Tabs are defined as four
spaces. Line numbers are displayed everywhere.

Backup files are not created and files are not automatically saved.

* Custom Global Keybindings

| f8  | open deft                                         |
| f12 | delete trailing whitespace                        |
| C-/ | Comments or uncomments the current region or line |

* Major Modes

** =text-mode=

A hook exists which will activate =auto-fill-mode= and
=flyspell-mode=. This means paragraphs have hard line breaks, and
spelling is checked on the fly, using aspell.

** =auctex-mode= and =latex-mode=

=auto-fill-mode=, =flyspell-mode= and =latex-math-mode= are all
activated when in =latex-mode=. The default TeX-engine is set to
=pdflatex=.

** =matlab-mode=

There are currently no customisation defined for =matlab-mode=.

** =mu4e=

For security reasons, my email configuration is stored in a separate
file.

* Minor Modes

** =company-mode=

Enabled globally. There a hook defined to make it work with LaTeX
properly.

* Custom Functions

** =journal-today=

This opens a text file for the current date in ~/Documents/Journal/. I
use this to store a journal.

** =comment-or-uncomment-region-or-line=

I pinched this off the web. I am sorry, but I cannot remember where
and did not store a reference. It is used to comment, or uncomment, a
region or a line. It is bound to C-/.
