name: elisp-check

on:
  push:
    branches: [ "master" , "main" ]
  pull_request:
    branches: [ "master" , "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - uses: leotaku/elisp-check@v1.3
        with:
          file: '*.el'
